var namespacei_text_sharp_1_1text_1_1rtf_1_1parser_1_1exceptions =
[
    [ "RtfParserException", "classi_text_sharp_1_1text_1_1rtf_1_1parser_1_1exceptions_1_1_rtf_parser_exception.html", "classi_text_sharp_1_1text_1_1rtf_1_1parser_1_1exceptions_1_1_rtf_parser_exception" ],
    [ "RtfUnknownCtrlWordException", "classi_text_sharp_1_1text_1_1rtf_1_1parser_1_1exceptions_1_1_rtf_unknown_ctrl_word_exception.html", "classi_text_sharp_1_1text_1_1rtf_1_1parser_1_1exceptions_1_1_rtf_unknown_ctrl_word_exception" ]
];